GET http://localhost:3000/0x0ae8b74cd2d566853715800c9927f879d6b76a37
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbnBhbmkiLCJwYXNzd29yZCI6ImtvbnBhbmkiLCJpYXQiOjE2MzUxMzUwMzl9.x2m2VEq9z5fotLRwrYCXv2BJIYqDwNEakJfW29SS-KI

###

POST http://localhost:3000/create
Content-Type: application/json

{
    "username": "konpani",
    "password": "konpani"
}